// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FollowUser(ctx context.Context, arg FollowUserParams) error
	GetFollowersEmails(ctx context.Context, arg GetFollowersEmailsParams) ([]string, error)
	GetFollowersIDs(ctx context.Context, followingID int64) ([]int64, error)
	GetFollowingEmails(ctx context.Context, arg GetFollowingEmailsParams) ([]string, error)
	GetFollowingIDs(ctx context.Context, followerID int64) ([]int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByIdAndEmail(ctx context.Context, arg GetUserByIdAndEmailParams) (User, error)
	GetUsersEmails(ctx context.Context, arg GetUsersEmailsParams) ([]string, error)
}

var _ Querier = (*Queries)(nil)
